name: Main

on: push

jobs:
  build-android:
    name: Build Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: cd example && flutter build apk

  build-ios:
    name: Build iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: CocoaPods setup workaround
        # CocoaPods 1.8.0 pre-installed according to https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#macos-1014
        # CocoaPods 1.7.x required for flutter-1.9.1 according to https://github.com/flutter/flutter/issues/41253
        run: |
          sudo gem uninstall cocoapods
          sudo gem install cocoapods -v 1.7.5
          pod setup
      - run: cd example && flutter build ios --no-codesign
